### ISSUE TITLE
Does this replace "docker login" partially or completely?

### ISSUE THREAD

**Issue by stevenscg** [adobe-platform/aws-ecr-login#1]
Hi @matthewdfuller. Thanks for sharing!

I'm already familiar with the standard aws cli commands for logging in with ECR:
```
$(aws ecr get-login)
```

When using only the `ecr-login.sh` script from within EC4, I can see the generated `config.json` and it looks correct, but I get errors accessing the registry until I do a "docker login".

I expected this script to eliminate the need to do any "docker login" commands.

Is that a valid expectation or does DC/OS (mentioned in the README) take the `.docker` tarball and do something else?

**Comment by matthewdfuller** [comment]
@stevenscg - when you launch an app through Marathon, there is a place you can pass `uris` as an array of file locations. This ecr-login repo will create the docker config, as well as a tarball in the directory, which you have to pass to the uris for the app. It wasn't originally designed to work with docker directly from the cli (although I don't see why it wouldn't). If you do a `docker login` where does the file get placed on your system? You may have to modify this script to point at that same location.

Also, which docker version are you on? They changed the format of the configs around 1.9 or so, switching from .dockercfg to .docker/config.json, and I don't think the old docker will recognize this newer format.

**Comment by stevenscg** [comment]
Hi Matt. Thanks for the info. The script works great and I really like the logging and error handling that you're doing.

I'm actually running it via cron on my docker hosts with a few alterations:
* Calling "docker login" at the end of the $registries loop
* Checking for a passed interval == 0 to give me a one-shot run.

Our docker project is greenfield, so we're rolling out 1.13 on RHEL/CentOS.

I was wondering if maybe the $AUTH_TOKEN used by ECR_JSON and ECR_JSON_PLAIN needed to be base64 decoded and split to separate the username and password elements.

My docker login logic looks like this at the moment:
```
        # Login to the registry
        # get-authorization-token returns a base64 encoded username:password
        # Separate the password
        # http://docs.aws.amazon.com/cli/latest/reference/ecr/get-authorization-token.html
        ECR_PASS=$(echo $AUTH_TOKEN | base64 -d | cut -d: -f2)
        docker login -u AWS -p $ECR_PASS -e none $ENDPOINT
```

**Comment by stevenscg** [comment]
I took a fresh look at this again just now. It does appear that the separate docker login commands are not needed.

Building up the "auths" object in `~/.docker/config.json` is completely sufficient in my testing and $AUTH_TOKEN does not need to be base64 decoded or split (to answer my own questions).

**Comment by matthewdfuller** [comment]
@stevenscg - great to hear, thanks! Glad you were able to resolve. Let me know if you run into any other issues, or feel free to PR as well if you find any improvements.
